#include <16F887.H>
#FUSES HS
#USE DELAY(CLOCK=20M)

#DEFINE XUNG1 PIN_D0 //5MS 
#DEFINE XUNG2 PIN_D1 //1MS MUC CAO, 2MS MUC THAP

UNSIGNED INT1 TT_XUNG2;//TRUE=MUC CAO, FALSE=MUC THAP

void main()
{
   OUTPUT_DRIVE(XUNG1);
   OUTPUT_DRIVE(XUNG2);
   
   TT_XUNG2=TRUE;
   OUTPUT_HIGH(XUNG1);
   OUTPUT_HIGH(XUNG2);
   
   SETUP_TIMER_0(T0_INTERNAL|T0_DIV_128); 
   SETUP_TIMER_1(T1_INTERNAL|T1_DIV_BY_1);
   SET_TIMER0(0);
   SET_TIMER1(0);
   
LAP:   
   IF (GET_TIMER0()>207)//5ms = 5000us/(0.2*128) = 207
   {
      SET_TIMER0(0);
      OUTPUT_TOGGLE(XUNG1);
   }
   
   IF ((GET_TIMER1()>5000) && (TT_XUNG2==TRUE)) //1000/(0.2*1)=5000
   {
      OUTPUT_LOW(XUNG2);
      SET_TIMER1(0);
      TT_XUNG2=FALSE;
   }
   ELSE IF (GET_TIMER1()>10000) //DELAY 2MS KHI XUNG 2 O MUC THAP
   {
      OUTPUT_HIGH(XUNG2);
      SET_TIMER1(0);
      TT_XUNG2=TRUE;
   }
   GOTO LAP;
}
