#include <16F887.H>
#DEVICE ADC=10
#FUSES HS
#USE DELAY(CLOCK=20M)

#define LCD_ENABLE_PIN  PIN_E2
#define LCD_RS_PIN      PIN_E0
#define LCD_RW_PIN      PIN_E1
#define LCD_DATA4       PIN_D4
#define LCD_DATA5       PIN_D5
#define LCD_DATA6       PIN_D6
#define LCD_DATA7       PIN_D7

#INCLUDE <LCD.C>

UNSIGNED INT16 ND1,ND2;

void main()
{
   SET_TRIS_D(0);
   SET_TRIS_E(0);
   
   LCD_INIT();
   
   SETUP_ADC(ADC_CLOCK_DIV_2);
   SETUP_ADC_PORTS(SAN0|SAN1|VSS_VDD);
LAP:

   SET_ADC_CHANNEL(0);
   DELAY_MS(10);
   ND1=READ_ADC()/2.046;// 10/4.884 = 2.046
   LCD_GOTOXY(1,1);
   PRINTF(LCD_PUTC,"TEMP1=%02LU C",ND1);
   LCD_GOTOXY(9,1);
   LCD_PUTC(0XDF);
   
   SET_ADC_CHANNEL(1);
   DELAY_MS(10);
   ND2=READ_ADC()/2.046;
   LCD_GOTOXY(1,2);
   PRINTF(LCD_PUTC,"TEMP2=%02LU C",ND2);
   LCD_GOTOXY(9,2);
   LCD_PUTC(0XDF);
   GOTO LAP;
}
